Repository beehive-lab/TornadoVM, pull requests merged in 2021-04, with the labels that each got.

#76 Fixup/unit-tests/amd
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLAMDScheduler.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/profiler/TestProfiler.java
Labels: bug

#81 [docs] Intel OpenCL drivers update
  assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
Labels: documentation

#83 [fix] ByteBuffer in the OCL event from static to non-static
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLEvent.java
Labels: bug

#84 Unsafe access removed from TornadoVMConfig and use JVMCI metaAccessProvider instead
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoCoreRuntime.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVMConfig.java
Labels: enhancement

#82 [fix] Device Information from MxM examples fixed
  examples/src/main/java/uk/ac/manchester/tornado/examples/compute/MatrixMultiplication1D.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/compute/MatrixMultiplication2D.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskSchedule.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/TaskMetaData.java
Labels: bug

#87 [dosc] README updated with an example of the expanded API (kernel par…
  README.md
  assembly/src/docs/14_PUBLICATIONS.md
Labels: documentation

#85 Runtime error when two tasks have the same name
  assembly/src/bin/tornado-test.py
  assembly/src/docs/15_FAQ.md
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskSchedule.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/exceptions/TornadoTaskRuntimeException.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/common/TornadoTestBase.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/fails/RuntimeFail.java
Labels: enhancement

#88 [release] TornadoVM 0.9
  INSTALL.md
  README.md
  assembly/pom.xml
  assembly/src/bin/tornadoLocalInstallMaven
  assembly/src/docs/1_INSTALL.md
  assembly/src/docs/CHANGELOG.md
  assembly/src/docs/Releases.md
  benchmarks/pom.xml
  drivers/drivers-common/pom.xml
  drivers/opencl-jni/pom.xml
  drivers/opencl/pom.xml
  drivers/pom.xml
  drivers/ptx-jni/pom.xml
  drivers/ptx/pom.xml
  examples/pom.xml
  matrices/pom.xml
  pom.xml
  runtime/pom.xml
  tornado-annotation/pom.xml
  tornado-api/pom.xml
  unittests/pom.xml
Labels: release

#91 [CodeGen] Fix kernel name for Lambda Expressions
  assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompiler.java
Labels: bug

#90 Hotfix/673/thanos
  assembly/src/docs/6_TORNADO_FLAGS.md
  assembly/src/docs/7_FPGA.md
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLCodeCache.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/RuntimeUtilities.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/Tornado.java
Labels: enhancement

#93 Support for TornadoMath functions in reductions
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFMANode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFPBinaryIntrinsicNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFPTernaryIntrinsicNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFPUnaryIntrinsicNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLIntBinaryIntrinsicNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLIntTernaryIntrinsicNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLIntUnaryIntrinsicNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXFPBinaryIntrinsicNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXFPUnaryIntrinsicNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXIntBinaryIntrinsicNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXIntUnaryIntrinsicNode.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/ReduceCodeAnalysis.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/MarkFloatingPointIntrinsicsNode.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/MarkIntIntrinsicNode.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/MarkIntrinsicsNode.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoFeatureExtraction.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoReduceReplacement.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsDoubles.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsFloats.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsIntegers.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsLong.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/tornadovmcontext/reductions/TestReductionsDoublesTornadoVMContext.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/tornadovmcontext/reductions/TestReductionsFloatsTornadoVMContext.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/tornadovmcontext/reductions/TestReductionsIntegersTornadoVMContext.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/tornadovmcontext/reductions/TestReductionsLongTornadoVMContext.java
Labels: enhancement
