Repository beehive-lab/TornadoVM, pull requests merged in 2021-07, with the labels that each got.

#131 [fix][refactor] Deprecate OCLWriteNode and PTXWriteNode and fix store…
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLLoweringProvider.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLWriteNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXLoweringProvider.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXWriteNode.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/arrays/TestArrays.java
Labels: bug

#132 [feat] TornadoVM support for a single VM per device
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskSchedule.java
Labels: bug, enhancement

#133 Register Graal Compiler Plugin for accessing the global number of threads in OpenCL/PTX
  assembly/src/bin/tornado-test.py
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXGraphBuilderPlugins.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/api/KernelPluginsTests.java
Labels: OpenCL, PTX, enhancement
