Repository beehive-lab/TornadoVM, pull requests merged in 2021-05, with the labels that each got.

#97 Remove redundant parameter table from the PTXLIRGenerator
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/backend/PTXBackend.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXLIRGenerationResult.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXLIRGenerator.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PrintfNode.java
Labels: clean-up

#99 Decouple task meta from the PTXModule
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXCodeCache.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXModule.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXScheduler.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXStream.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXInstalledCode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXCompilationResult.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXCompiler.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/tests/TestPTXTornadoCompiler.java
Labels: bug

#98 Unload PTX/CUDA modules when resetting the code cache
  drivers/ptx-jni/src/main/cpp/source/PTXModule.cpp
  drivers/ptx-jni/src/main/cpp/source/PTXModule.h
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXCodeCache.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXModule.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXInstalledCode.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoInstalledCode.java
Labels: bug

#96 Fix dataflow analysis to retrieve data accesses
  assembly/src/bin/tornado-test.py
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLAMDScheduler.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLFPGAScheduler.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLGPUScheduler.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLJIT.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/asm/OCLAssembler.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/backend/OCLBackend.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompilationResultBuilder.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompiler.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLNodeLIRBuilder.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLCompilableTask.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/tests/TestOpenCLJITCompiler.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXCompiler.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXNodeLIRBuilder.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/tests/TestPTXJITCompiler.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoAutoParalleliser.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoDataflowAnalysis.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoShapeAnalysis.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoSketchTierContext.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoGraphBuilder.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/nodes/ValueNode.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/sketcher/Sketch.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/sketcher/SketchRequest.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/sketcher/TornadoSketcher.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/CompilableTask.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskSchedule.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/TaskMetaData.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/Access.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/tasks/TestMultipleFunctions.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/tornadovmcontext/api/TestCombinedTaskSchedule.java
Labels: bug

#101 Add option to inline during bytecode parsing
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXGraphBuilderPlugins.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
  pom.xml
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
Labels: clean-up, enhancement

#102 [fix] Compilation errors fixed in JDK11 due to JMH version update
  benchmarks/src/main/java/module-info.java
Labels: bug

#95 Fix floating reads
  assembly/src/examples/generated/virtualDevice/virtualDeviceFeaturesCPU.json
  assembly/src/examples/generated/virtualDevice/virtualDeviceFeaturesGPU.json
  assembly/src/examples/generated/virtualDevice/virtualDeviceKernelCPU.cl
  assembly/src/examples/generated/virtualDevice/virtualDeviceKernelGPU.cl
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDriver.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLLowTier.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/GroupIdNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/LocalArrayNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoFloatingReadReplacement.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDriver.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXLowTier.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXNodeLIRBuilder.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXArithmeticTool.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/GroupIdNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/LocalArrayNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/phases/TornadoFloatingReadReplacement.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoCoreRuntime.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/Tornado.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoDriver.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoRuntimeCI.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/atomics/TestAtomics.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/common/TornadoTestBase.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/common/TornadoVMOpenCLNotSupported.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/common/TornadoVMPTXNotSupported.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/loops/TestLoops.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestMath.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/profiler/TestProfiler.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/tools/TornadoHelper.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/virtual/TestVirtualDeviceFeatureExtraction.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/virtual/TestVirtualDeviceKernel.java
Labels: bug

#100 Fix update reference for COPY_IN objects
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLKernelScheduler.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLInstalledCode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/profiler/TimeProfiler.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/GlobalObjectState.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/LocalObjectState.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskSchedule.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/GridTask.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskSchedule.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/mm/TornadoGlobalObjectState.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/profiler/ProfileInterface.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/profiler/ProfilerType.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/dynsize/Resize.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/profiler/TestProfiler.java
Labels: bug, clean-up

#106 Hotfix for disabling FixReads to make kfusion run on Nvidia GPUs
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLLowTier.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
Labels: bug

#105 [docs] List of supported drivers updated
  assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
Labels: documentation

#103 [Fix] OCLKind/PTXKind inconsistency in code gen
  assembly/src/examples/generated/virtualDevice/virtualDeviceKernelGPU.cl
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLKind.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/LocalArrayNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXKind.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/LocalArrayNode.java
Labels: enhancement

#109 [docs] New OpenCL driver for Linux supported
  assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
Labels: documentation

#111 Fix scheduling when multiple task schedules use the same Java method
  assembly/src/examples/generated/add.ptx
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXCodeUtil.java
Labels: bug

#112 Change data transfers to be blocking by passing CL_TRUE instead of calling clWaitForEvents
  drivers/opencl-jni/src/main/cpp/source/OCLCommandQueue.cpp
Labels: OpenCL

#114 Release OCL events when calling device reset
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLEventsWrapper.java
Labels: OpenCL, bug
