Repository beehive-lab/TornadoVM, pull requests merged in 2021-08, with the labels that each got.

#134 [refactor] event.getExecutionTime -> event.getElapsedTime
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLEvent.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLKernelScheduler.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLInstalledCode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXEvent.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/EmptyEvent.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskSchedule.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/ProfiledAction.java
Labels: clean-up, refactor

#136 [docs] List of NVIDIA drivers supported updated
  assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
Labels: documentation

#135 Refactoring of Events for both OpenCL and PTX backends
  drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/EventDescriptor.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLEvent.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLEventPool.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXEvent.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXEventPool.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXStream.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/EmptyEvent.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/Tornado.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoLogger.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/Event.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/SynchronisationPoint.java
Labels: clean-up, documentation, refactor

#141 [docs] Minor updates in README.md & 15_FAQ.md
  README.md
  assembly/src/docs/15_FAQ.md
Labels: documentation
