Repository beehive-lab/TornadoVM, pull requests merged in 2021-06, with the labels that each got.

#115 Fix 2D arrays for OpenCL
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLArrayWrapper.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/matrices/TestMatrices.java
Labels: OpenCL

#113 Fix loop conditions when data flow is attached to the LoopBegin node
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/asm/OCLAssembler.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLBlockVisitor.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompilationResultBuilder.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLControlFlow.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/loops/TestLoops.java
Labels: OpenCL, bug

#122 [refactor] GridTask renamed to GridScheduler
  README.md
  assembly/src/docs/21_KERNEL_CONTEXT.md
  examples/src/main/java/uk/ac/manchester/tornado/examples/compute/MatrixMultiplication1D.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/compute/MatrixMultiplication2D.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/compute/NBody.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/fpga/VectorAddIntGridScheduler.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/BFS.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/BlackAndWhiteTransform.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/Euler.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/HilbertMatrix.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/Mandelbrot.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/MatrixMultiplication1D.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/MatrixMultiplication2DV1.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/MatrixMultiplication2DV2.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/Montecarlo.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/NBody.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/compute/RenderTrack.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/matrices/MatrixMul2DLocalMemory.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/reductions/ReductionsGlobalMemory.java
  examples/src/main/java/uk/ac/manchester/tornado/examples/kernelcontext/reductions/ReductionsLocalMemory.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskSchedule.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/AbstractTaskGraph.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/GridScheduler.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/KernelContext.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskSchedule.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoAPI.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/dynsize/Resize.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/grid/TestGrid.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/grid/TestGridScheduler.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/api/TestCombinedTaskSchedule.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/api/TestVectorAdditionKernelContext.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/matrices/TestMatrixMultiplicationKernelContext.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsDoublesKernelContext.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsFloatsKernelContext.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsIntegersKernelContext.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsLongKernelContext.java
Labels: enhancement, proposal

#121 [FPGA] Enhancement of Xilinx OpenCL backend
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLCodeCache.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLHighTier.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLNodeLIRBuilder.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/IntelUnrollPragmaNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/XclPipelineAttribute.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/XilinxPipeliningPragmaNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoFPGAPragmas.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDeviceContext.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoDeviceContext.java
Labels: enhancement

#125 [fix] FMA LIR Type fixed for ternary nodes
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLArithmeticTool.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXArithmeticTool.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestMath.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestTornadoMathCollection.java
Labels: OpenCL, PTX, compiler

#126 [tests] Compute-Test added as unittests
  assembly/src/bin/tornado-test.py
  examples/src/main/java/uk/ac/manchester/tornado/examples/compute/NBody.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/ComputeTests.java
Labels: OpenCL, PTX, enhancement

#127 Support for `getArray` for vector types in TornadoVM
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/VectorPlugins.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/vector/GetArrayNode.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/vector/VectorValueNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXVectorPlugins.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/GetArrayNode.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/vector/VectorValueNode.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/vectortypes/TestFloats.java
Labels: OpenCL, PTX, enhancement

#128 [refactor] Changing --debug from displaying the grid dimensions
  assembly/src/bin/tornado
  assembly/src/bin/tornado-test.py
  assembly/src/docs/6_TORNADO_FLAGS.md
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLKernelScheduler.java
  drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXStream.java
  runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
Labels: enhancement

#129 Fix brackets issue on some extra edge cases
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLBlockVisitor.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompilationResultBuilder.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLNodeLIRBuilder.java
  drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLLIRStmt.java
  unittests/src/main/java/uk/ac/manchester/tornado/unittests/codegen/CodeGen.java
Labels: bug
