Repository beehive-lab/TornadoVM, pull requests merged in 2023-11, with the labels that each got.

#279 [fix] fix --profiler flag in tornado-benchmarks.py script
  tornado-assembly/src/bin/tornado-benchmarks.py
Labels: bug, clean-up

#278 README documentation updated
  README.md
Labels: documentation

#280 Fix GraalVM JDK21 download urls in installer_config.py
  bin/installer_config.py
Labels: bug, installation

#282 [fix] benchmark classpath with JMH option
  tornado-assembly/src/bin/tornado-benchmarks.py
Labels: bug

#281 [fix] Installer with no polyglot configuration
  bin/tornadovm-installer
Labels: bug, installation

#285 Reformat KernelContext table
  docs/source/programming.rst
Labels: documentation

#288 Fix aws s3 configuration usage in aws_post_processing.sh
  tornado-assembly/src/bin/aws_post_processing.sh
Labels: bug, fpga, AWS

#286 Move input sizes check to also check for tornado arrays
  docs/source/programming.rst
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/BatchConfiguration.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/batches/TestBatches.java
Labels: bug, runtime
