Repository beehive-lab/TornadoVM, pull requests merged in 2024-07, with the labels that each got.

#468 Cleanup AbstractMetaData class
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLCodeCache.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLInstalledCode.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/TaskMetaData.java
Labels: refactor

#470 Update README.md
  README.md
Labels: documentation

#473 Include plugin to include TornadoVM sources in the final build
  pom.xml
Labels: documentation, installation

#474 [refactor] loopIndexInWrite implementation moved to its root interface
  tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/TornadoBufferProvider.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/JVMMapping.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoXPUDevice.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/batches/TestBatches.java
Labels: runtime, refactor

#482 When TornadoVM raises OOM, it prints a possible action to fix it
  tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/TornadoBufferProvider.java
Labels: runtime, memory

#484 TornadoMath double version of trigonometric functions added
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/math/TornadoMath.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestTornadoMathCollection.java
Labels: API

#486 Add URL for JDK Temurin Windows
  bin/installer_config.py
Labels: installation, windows

#488 [fix] Added fp64 kind for radians operations in PTX compiler
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXFPUnaryIntrinsicNode.java
Labels: bug, PTX

#493 [test] Update whitelist for PTX backend
  tornado-assembly/src/bin/tornado-test
Labels: tests, jenkins

#494 Add test to trigger unsupported input when user try to offload directly `MemorySegments`
  tornado-assembly/src/bin/tornado-test
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestMemorySegmentsAsType.java
Labels: tests

#487 [feat][api] Prebuilt API redesign and simplification
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/AccessorParameters.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraph.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraphInterface.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/PrebuiltTaskPackage.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/TaskPackage.java
  tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/dgemm/DgemmTornado.java
  tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/sgemm/SgemmTornado.java
  tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/arrays/ArrayAddIntPrebuilt.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/TaskUtils.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/PrebuiltTask.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/atomics/TestAtomics.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/prebuilt/PrebuiltTest.java
Labels: proposal, API

#509 Add `quickPass` option to skip heavy tests in tornado-test script
  Makefile
  tornado-assembly/src/bin/tornado-test
Labels: tests

#514 [hotfix] TornadoVM installer script fixed to build with GraalVM JDK 21
  bin/installer_config.py
Labels: bug, installation

#513 Issue #506 has been fixed.
  pom.xml
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLPrintf.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLTPrintf.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/PrintfNode.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/TPrintfNode.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/TestHello.java
Labels: OpenCL, fix
