Repository beehive-lab/TornadoVM, pull requests merged in 2024-08, with the labels that each got.

#527 [spirv] flag to be able to run with prev. versions of SPIR-V 1.2
  docs/source/spirv-backend.rst
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDevice.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVBackendImpl.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
Labels: spirv

#538 [docs] fix badges in the README file
  README.md
Labels: documentation

#531 [deps] Level Zero JNI v0.1.4 updated
  tornado-drivers/spirv/pom.xml
Labels: dependencies, spirv, level-zero

#542 [build][spirv] Download tagged versions for dependencies (spirv-toolkit and level zero JNI)
  bin/compile
  bin/installer_config.py
  bin/tornadovm-installer
Labels: installation, spirv, level-zero

#541 [fix] Data Access for PrebuiltTaskGraph fixed
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/PrebuiltTaskPackage.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLPrebuiltTask.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/TaskUtils.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/PrebuiltTask.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/TaskDataContext.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/prebuilt/PrebuiltTest.java
Labels: API, runtime

#543 [fix] check style conditions and the exception message for FP16
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/tensors/Shape.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/OCLFP16SupportPhase.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoVMGraphCompiler.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/sketcher/TornadoSketcher.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestMemorySegmentsAsType.java
Labels: code-style

#532 Fix ComputeAorta/OCK thread scheduler for the OpenCL backend
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLScheduler.java
Labels: OpenCL, runtime, scheduler

#540 Fix issue with the TestReductionsAutomatic unittest
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
Labels: bug

#533 Remove param pi nodes
  tornado-assembly/src/bin/tornado-test
  tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/code/CodeUtil.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/backend/OCLBackend.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoTaskSpecialisation.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/phases/TornadoTaskSpecialisation.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/phases/TornadoTaskSpecialization.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/functional/TestLambdas.java
Labels: compiler, runtime, fix

#544 Fix the device switching for all backends
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/SchedulableTask.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/TornadoDevice.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLBackendImpl.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContextInterface.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDeviceContext.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXBackendImpl.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVBackendImpl.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVDeviceContext.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/tests/TestVM.java
  tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/arrays/ArrayAddInt.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/JVMMapping.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoXPUDevice.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/CompilableTask.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/PrebuiltTask.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractRTContext.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/ScheduleContext.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/common/TornadoTestBase.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/profiler/TestProfiler.java
Labels: OpenCL, PTX, runtime, spirv

#545 [test] Removed double entry from tornado-test
  tornado-assembly/src/bin/tornado-test
Labels: tests, refactoring

#546 [release] TornadoVM 1.0.7
  README.md
  docs/source/CHANGELOG.rst
  docs/source/conf.py
  docs/source/installation.rst
  pom.xml
  tornado-annotation/pom.xml
  tornado-api/pom.xml
  tornado-assembly/pom.xml
  tornado-assembly/src/bin/tornado-test
  tornado-benchmarks/pom.xml
  tornado-drivers/drivers-common/pom.xml
  tornado-drivers/opencl-jni/pom.xml
  tornado-drivers/opencl/pom.xml
  tornado-drivers/pom.xml
  tornado-drivers/ptx-jni/pom.xml
  tornado-drivers/ptx/pom.xml
  tornado-drivers/spirv/pom.xml
  tornado-examples/pom.xml
  tornado-matrices/pom.xml
  tornado-runtime/pom.xml
  tornado-unittests/pom.xml
Labels: release
