Repository beehive-lab/TornadoVM, pull requests merged in 2025-05, with the labels that each got.

#674 [doc] fix project links in README
  README.md
Labels: documentation

#673 [nit] Avoid bytecode logging for header bytecode during VM warm-up.
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
Labels: clean-up

#675 Apply rescheduling of true branches only for conditions
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompilationResultBuilder.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXCompilationResultBuilder.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/SPIRVCompilationResultBuilder.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/ComputeTests.java
Labels: compiler, OpenCL, PTX, spirv, fix

#677 [compiler] Fix 1.0/sqrt(x) replacement with native rsqrt(x) function
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/InverseSquareRootPhase.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/phases/InverseSquareRootPhase.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/phases/InverseSquareRootPhase.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestMath.java
Labels: fix

#676 Add unit tests for Transformer Compute Kernels expressed with a mix of KernelContextApi and `@Paralllel` API
  tornado-assembly/src/bin/tornado-test
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/TransformerKernelsTest.java
Labels: tests

#678 [fix] Added guard conditions for UPS metrics when profiling across all backends
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLKernelScheduler.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/SPIRVLevelZeroInstalledCode.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/SPIRVOCLInstalledCode.java
Labels: fix

#681 Fix closing bracket for flash attention
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLBlockVisitor.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/codegen/CodeGenTest.java
Labels: bug, OpenCL

#679 Matrix-Vector Row-Major Compute Example
  tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/compute/MatrixVectorRowMajor.java
Labels: tests

#683 Mark Flash Attention Unittest Unsupported for SPIR-V
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/codegen/CodeGenTest.java
Labels: spirv, tests
