Repository beehive-lab/TornadoVM, pull requests merged in 2025-01, with the labels that each got.

#607 [docs] WSL installation and configuration added
  docs/source/installation.rst
Labels: documentation, windows

#609 [docs] Updated instructions for RISC-V
  docs/source/installation.rst
Labels: documentation, riscv

#606 [fix] Update data sizes in tornado-benchmarks.py
  tornado-assembly/src/bin/tornado-benchmarks.py
Labels: fix, benchmarking

#608 [feat] Individual selection of Level Zero and/or OpenCL runtimes for SPIR-V
  docs/source/spirv-backend.rst
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLPragmaUnroll.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVBackendImpl.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVOpenCLPlatform.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVRuntimeImpl.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
Labels: OpenCL, runtime, spirv

#610 Maven dependency updated
  bin/installer_config.py
Labels: installation, dependencies

#612 Enable colours in maven build
  bin/compile
Labels: installation

#614 [fix] Update Benchmark flag in Jenkinsfile
  Jenkinsfile
Labels: jenkins

#615 [style] Fix check style of source code
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Half16.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Half2.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Half8.java
  tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/BenchmarkDriver.java
  tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/TornadoBufferProvider.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/sketcher/TornadoSketcher.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/PrebuiltTask.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/ComputeTests.java
Labels: code-style

#616 [fix] Atomic operations in OpenCL with the Kernel API
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLUnary.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/DecAtomicNode.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/IncAtomicNode.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoAtomicsScheduling.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/atomics/TestAtomics.java
Labels: fix

#617 [release] v1.0.10
  README.md
  bin/tornadovm-installer
  docs/source/CHANGELOG.rst
  docs/source/conf.py
  docs/source/installation.rst
  pom.xml
  tornado-annotation/pom.xml
  tornado-api/pom.xml
  tornado-assembly/pom.xml
  tornado-assembly/src/bin/tornado-test
  tornado-benchmarks/pom.xml
  tornado-drivers/drivers-common/pom.xml
  tornado-drivers/opencl-jni/pom.xml
  tornado-drivers/opencl/pom.xml
  tornado-drivers/pom.xml
  tornado-drivers/ptx-jni/pom.xml
  tornado-drivers/ptx/pom.xml
  tornado-drivers/spirv/pom.xml
  tornado-examples/pom.xml
  tornado-matrices/pom.xml
  tornado-runtime/pom.xml
  tornado-unittests/pom.xml
Labels: release
