Repository beehive-lab/TornadoVM, pull requests merged in 2025-03, with the labels that each got.

#628 Device Filtering Fixed + New filters by device type and device names
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoDeviceMap.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestDevices.java
Labels: API, runtime, fix

#627 [Feature] Implement shared buffer functionality of multiple `TaskGraphs` on the same device under `persistOnDevice` and `consumeFromDevice` API extensions
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/ImmutableTaskGraph.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraph.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraphInterface.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutor.java
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoTaskGraphInterface.java
  tornado-assembly/src/bin/tornado-test
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoGraphBuilder.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoVMBytecodeBuilder.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoVMBytecodes.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/nodes/OnDeviceObjectNode.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/LocalObjectState.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestSharedBuffers.java
Labels: API, refactor, feature

#629 Hotfix for the whitelist of some test-devices unittests
  tornado-assembly/src/bin/tornado-test
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestDevices.java
Labels: API, tests

#632 Build with maven in single-threaded mode
  Makefile
  Makefile.mak
  bin/compile
  bin/tornadovm-installer
Labels: installation

#633 Add Unit Test for Executing Multiple Task Graphs with Different Grid Schedulers
  tornado-assembly/src/bin/tornado-test
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestChainOfGridSchedulers.java
Labels: API, tests

#636 [logs] Bytecode interpreter with object size
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/DebugInterpreter.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
Labels: runtime

#635 [hotfix] Update inner node for local memory allocation to be ValueNode instead of ConstantNode
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/LocalArrayNode.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXGraphBuilderPlugins.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/LocalArrayNode.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/plugins/SPIRVGraphBuilderPlugins.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/nodes/LocalArrayNode.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/codegen/CodeGenTest.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsDoublesKernelContext.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsFloatsKernelContext.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsIntegersKernelContext.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsLongKernelContext.java
Labels: bug

#641 [develop-track] Bump version to 1.1.0-dev in pom.xml and related files
  bin/tornadovm-installer
  pom.xml
  tornado-annotation/pom.xml
  tornado-api/pom.xml
  tornado-assembly/pom.xml
  tornado-assembly/src/bin/tornado-test
  tornado-benchmarks/pom.xml
  tornado-drivers/drivers-common/pom.xml
  tornado-drivers/opencl-jni/pom.xml
  tornado-drivers/opencl/pom.xml
  tornado-drivers/pom.xml
  tornado-drivers/ptx-jni/pom.xml
  tornado-drivers/ptx/pom.xml
  tornado-drivers/spirv/pom.xml
  tornado-examples/pom.xml
  tornado-matrices/pom.xml
  tornado-runtime/pom.xml
  tornado-unittests/pom.xml
Labels: refactoring

#644 [hotfix] executionFrame setter after merge
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
Labels: bug

#645 [rt] Memory dealloc by default when closing an execution plan resource
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLAtomicsBuffer.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLMemoryManager.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
Labels: runtime, memory

#642 Compiler Plugins for `acosh` and `asinh` math functions
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/math/TornadoMath.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/asm/OCLAssembler.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLMathPlugins.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLBuiltinTool.java
  tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFPUnaryIntrinsicNode.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/plugins/SPIRVMathPlugins.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/lir/SPIRVBuiltinTool.java
  tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/nodes/SPIRVFPUnaryIntrinsicNode.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestTornadoMathCollection.java
Labels: compiler, API

#646 [hotfix] Fix to prevent issue with shared buffer allocation when not all buffers are present in args
  tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutor.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
  tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestSharedBuffers.java
Labels: bug

#649 [refactor] Change fast mode to live mode in tornado-test
  tornado-assembly/src/bin/tornado-test
Labels: tests, usability

#651 [ptx] Memory region mapping with offsets fixed
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXStream.java
  tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXMemorySegmentWrapper.java
Labels: PTX, runtime, fix

#652 [loging] Enhance deallocation logging to include materialization of action
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/DebugInterpreter.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
Labels: feature

#653 [hotfix] Object repetition with shared buffers on ON_DEVICE bytecodes
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoVMBytecodeBuilder.java
  tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/nodes/OnDeviceObjectNode.java
Labels: fix

#654 [test] Add loop condition test in white list
  tornado-assembly/src/bin/tornado-test
Labels: jenkins

#655 [release] TornadoVM 1.1.0
  README.md
  bin/tornadovm-installer
  docs/source/CHANGELOG.rst
  docs/source/conf.py
  docs/source/installation.rst
  pom.xml
  tornado-annotation/pom.xml
  tornado-api/pom.xml
  tornado-assembly/pom.xml
  tornado-assembly/src/bin/tornado-test
  tornado-benchmarks/pom.xml
  tornado-drivers/drivers-common/pom.xml
  tornado-drivers/opencl-jni/pom.xml
  tornado-drivers/opencl/pom.xml
  tornado-drivers/pom.xml
  tornado-drivers/ptx-jni/pom.xml
  tornado-drivers/ptx/pom.xml
  tornado-drivers/spirv/pom.xml
  tornado-examples/pom.xml
  tornado-matrices/pom.xml
  tornado-runtime/pom.xml
  tornado-unittests/pom.xml
Labels: release
